inherit_from: .rubocop_todo.yml

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 160

# TODO: Down it to 30, 3 times more than Rubocop default
Metrics/MethodLength:
  Max: 35

Metrics/PerceivedComplexity:
  Enabled: false